### ISSUE TITLE
Metrics TODO list

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/cloud-changelog#11]
- [x] Allow to query spans/events from metrics
- [x] Provide filter facets for metrics
- [x] Improve UI for switching between table/grid metric views
- [x] Allow to quickly change group by in the grid
- [x] Allow to add/edit text gauges
- [x] Support table visualization in the grid view
- [x] Support heatmaps in the grid view
- [x] Allow to customize grid size
- [x] Support deploy annotations in metrics and spans
- [x] Allow to customize colors for timeseries (just like units)
- [x] Start using GridStack.js
- [x] Allow to edit dashboards using YAML

See https://github.com/uptrace/cloud-changelog#uptrace-cloud-changelog for details

**Comment by vmihailenco** [comment]
This is all done for some time: https://app.uptrace.dev/metrics/
